# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['prototype/desktop/app.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('prototype/config/config.json', 'prototype/config'),
    ],
    hiddenimports=[
        'prototype.runtime',
        'prototype.runtime.alfa_runtime',
        'prototype.kernel',
        'prototype.executive',
        'prototype.decision',
        'prototype.reflection',
        'prototype.learning',
        'prototype.memory',
        'prototype.memory.persistent_memory',
        'prototype.memory.memory_manager',
        'prototype.provider',
        'prototype.provider.mock_provider',
        'prototype.provider.nvidia_provider',
        'prototype.provider.openrouter_provider',
        'prototype.provider.ollama_provider',
        'prototype.tools',
        'prototype.tools.builtin_tools',
        'prototype.plugins',
        'prototype.worker',
        'prototype.worker.base_worker',
        'prototype.worker.worker_registry',
        'prototype.worker.worker_scheduler',
        'prototype.worker.worker_lifecycle',
        'prototype.worker.worker_manager',
        'prototype.worker.echo_worker',
        'prototype.cognition',
        'prototype.cognition.cognition_runtime',
        'prototype.execution',
        'prototype.planner',
        'prototype.services',
        'prototype.voice',
        'prototype.agent',
        'prototype.desktop',
        'prototype.desktop.views',
        'sqlite3',
        'PySide6',
    ],

    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AlfaDesktop',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
